## $MK4_DIST_D/src/postproc/linkdata/Makefile
SHELL := /bin/ksh

##-----------------------------------------------------------------------------
ifeq "$(MK4_MK_ENV)" ""
  include $(shell echo $${PWD%/src/*})/cfg/env.mk
  default $(MAKECMDGOALS) :
	@mkdir -p $(MK4_MK_BLD_D)
	@$(MAKE) -f $(MK4_MK_SRC_D)/Makefile -C $(MK4_MK_BLD_D) $(MAKECMDGOALS) 

##-----------------------------------------------------------------------------
else # ifeq "$(MK4_MK_ENV)" ""
  include $(MK4_MK_CFG_D)/common.mk
  include $(MK4_MK_CFG_D)/$(MK4_MK_ARCH).mk 

  ##---------------------------------------------------------------------------
  language := c

  ##---------------------------------------------------------------------------
  ## prg
  prg := linkdata
  prg_srcs  := $(strip \
   alloc_lists.c     file_list.c       make_flinks.c     parent_root.c \
   cleanup.c         linkdata.c        make_link.c       parse_cmdline.c \
   dir_list.c        make_clinks.c     make_rlinks.c     read_afiles.c \
   type_3.c \
  )
  prg_libs := afio mk4util m c
  prg_lpath :=  $(MK4_MK_LIB_D)

  ##
  ipath := $(MK4_MK_INC_D)

  ##
  include $(MK4_MK_CFG_D)/rules.mk 

##-----------------------------------------------------------------------------
endif # ifeq "$(MK4_MK_ENV)" ""
