/*  numeric message codes for Mark IV messages - see message_structs.h  */
#define GENERATE_ROOT          0x01
#define ROOT_COMPLETE          0x02
#define ROOT_FAILURE           0x03
#define CONFIGURE_CORRELATOR   0x04
#define PROGRAM_CONTROL        0x05
#define CU_RESOURCE_ERROR      0x06
#define CORRELATOR_ABORT       0x07
#define CORRELATOR_INITIALIZED 0x08
#define SET_COT_CLOCK          0x09
#define INITIALIZE_SUS         0x0a
#define CONFIGURE_SUS          0x0b
#define SUS_CONFIGURED         0x0c
#define CANT_MOUNT_TAPE        0x0d
#define POS_TO_TOT             0x0e
#define VALID_TIME             0x0f
#define SU_COMMAND             0x10
#define SYNCHRONIZE_TAPES      0x11
#define DPU_COMMAND            0x12
#define START_ROT_CLOCK        0x13
#define INITIALIZE_HARDWARE    0x14
#define REMOVE_STATION         0x15
#define SEND_COND_STATUS       0x16
#define COND_STATUS            0x17
#define MOUNT_REQUEST          0x18
#define SUS_INITIALIZED        0x19
#define TERMINATE_SELF         0x1a
#define ERROR_MESSAGE          0x1b
#define CU_CONFIGURATION       0x1c
#define SEND_TAPE_STATUS       0x1d
#define TAPE_STATUS            0x1e
#define TC_MSGHDR              0x1f
#define STREAM_CONTROL         0x20
#define REORDER_STREAMS        0x21
#define INITIALIZE_CORRELATOR  0x22
#define SEND_TAPE_INFO         0x23
#define TAPE_INFO              0x24
#define SEND_TIMES             0x25
#define CURRENT_TIMES          0x26
#define INITIALIZE_CRATE       0x27
#define CRATE_STATUS           0x28
#define REPOS_TO_TOT           0x29
#define CORRELATOR_STATS       0x2a
#define END_TASK               0x2b
#define MOUNT_STATUS           0x2c
#define DISMOUNT_TAPE          0x2d
#define CORRTASK_COMPLETE      0x2e
#define CANT_FIND_TIME         0x2f
#define SU_CONFIG_ERROR        0x30
#define TASK_STATUS            0x31
#define ALL_MOUNTED            0x32
#define TRANSMIT_FFS           0x33
#define REALTIME_DISPLAY       0x34
#define REALTIME_DATA          0x35
#define INITIALIZE_MK5         0x36
#define SEND_M5_STATUS         0x37
#define M5_STATUS              0x38
#define FIND_NEXT_HEADER       0x39
#define HEADER_CONTENTS        0x3a
#define CONFIGURE_SCAN         0x3b
#define MODEL_DATA             0x3c
#define PCAL_REQUEST           0x3d
#define PCAL_DATA              0x3e
#define SCOUNT_REQUEST         0x3f
#define SCOUNT_DATA            0x40
#define ABORT_SCAN             0x41
#define MOUNT_CHANGE           0x42
#define ASCII_MESSAGE          0x43
#define LOOKUP_SCAN            0x44
#define SCAN_BOUNDS            0x45
#define SEND_DIRECTORY         0X46
#define DIRECTORY_CHUNK        0x47
#define PLAYBACK_CONTROL       0x48


#define SU_RESPONSE           0x100 
