## $MK4_DIST_D/src/postproc/sub/x_fplot/Makefile
SHELL := /bin/ksh

##-----------------------------------------------------------------------------
ifeq "$(MK4_MK_ENV)" ""
  include $(shell echo $${PWD%/src/*})/cfg/env.mk
  default $(MAKECMDGOALS) :
	@mkdir -p $(MK4_MK_BLD_D)
	@$(MAKE) -f $(MK4_MK_SRC_D)/Makefile -C $(MK4_MK_BLD_D) $(MAKECMDGOALS) 

##-----------------------------------------------------------------------------
else # ifeq "$(MK4_MK_ENV)" ""
  include $(MK4_MK_CFG_D)/common.mk
  include $(MK4_MK_CFG_D)/$(MK4_MK_ARCH).mk 

  ##---------------------------------------------------------------------------
  language := c

  ##---------------------------------------------------------------------------

  ## lib
  lib := libx_fplot.a
  lib_srcs := $(strip \
   close_x_fplot.c get_gc.c show_x_fplot.c pgbreak_fplot.c open_x_fplot.c \
   too_small.c getfont_fplot.c print_x_fplot.c hcopy_x_fplot.c \
  )

  #
  ipath := $(MK4_MK_INC_D) 

  ##
  include $(MK4_MK_CFG_D)/rules.mk 

##-----------------------------------------------------------------------------
endif # ifeq "$(MK4_MK_ENV)" ""
