## $MK4_DIST_D/src/correlator/CorAsc2/Makefile
SHELL := /bin/ksh

##-----------------------------------------------------------------------------
ifeq "$(MK4_MK_ENV)" ""
  include $(shell echo $${PWD%/src/*})/cfg/env.mk
  default $(MAKECMDGOALS) :
	@mkdir -p $(MK4_MK_BLD_D)
	@$(MAKE) -f $(MK4_MK_SRC_D)/Makefile -C $(MK4_MK_BLD_D) $(MAKECMDGOALS) 

##-----------------------------------------------------------------------------
else # ifeq "$(MK4_MK_ENV)" ""
  include $(MK4_MK_CFG_D)/common.mk
  include $(MK4_MK_CFG_D)/$(MK4_MK_ARCH).mk 

  ##---------------------------------------------------------------------------
  language := c
  CC := gcc
  CFLAGS :=
  LDFLAGS :=

  ##---------------------------------------------------------------------------
  ## prg
  prg := CorAsc2
  prg_srcs := $(strip \
   CorAsc2.c \
  )
  prg_libs := m c

  ##
  ipath := $(MK4_MK_INC_D) 

  ##
  include $(MK4_MK_CFG_D)/rules.mk 

##-----------------------------------------------------------------------------
endif # ifeq "$(MK4_MK_ENV)" ""
