#!/bin/ksh
# $MK4_DIST_D/src/scripts/share/cleanmess 

#-------------------------------------------------------------------------------
me="`basename $0`"
. $MK4_CONF_D/mk4.conf

#-------------------------------------------------------------------------------
rdoa all rq correlator kp Log
rm -f $TMP/msg.*
