#!/bin/csh 
# count 
# Set up an xterm with counts (which see) therein 

#-------------------------------------------------------------------------------
set myname = $0
set me = $myname:t 
if ( $?LOGNAME ) then 
  setenv USER $LOGNAME  
else if ( $?USER ) then 
  setenv LOGNAME $USER 
endif 
if ( $?BIN ) then 
  setenv BIN /correlator/bin
endif 
if ( ! $?DISPLAY ) then 
  echo "%{me}:  DISPLAY is not set; I just can't go on this way! " 
  exit ( -1 ) 
endif 
echo "${me}:  Send an xterm to $DISPLAY, which must be in X mode. " 
xterm -title "Read Counter" -geometry 40x11-1-1 \
    -bg gray85 -fg black -e $BIN/counts &
echo "${me}:  OK " 

