#!/bin/ksh
# $MK4_DIST_D/src/scripts/share/endall

#-------------------------------------------------------------------------------
. $MK4_CONF_D/mk4.conf

#-------------------------------------------------------------------------------
rdoa all mq all
sendnote testprogs 0x1a 0x0 0x0 # send self-terminate to everyone but mailers

##
sleep 2
rdoa all kp correlator rq correlator
rm -f $TMP/msg.*
