#!/bin/ksh
# $MK4_DIST_D/src/scripts/share/endmailers

me="`basename $0`"

#-------------------------------------------------------------------------------
. $MK4_CONF_D/mk4.conf

#-------------------------------------------------------------------------------
rdoa all kp mailer rq mailer
rm -f $TMP/txm-*.log
rm -f $TMP/rxm-*.log
