#
# $Id$
#

SUBDIRS = .

AM_CPPFLAGS = -I. @HEADER_INCPATH_STR@ @CMAKE_C_FLAGS@

AM_CPPFLAGS += ${FFTW3_CFLAGS} ${X_CFLAGS} -I${PGPLOT_DIR}

pkginclude_HEADERS = @HEADER_BASENAMES_STR@

pkglib_LTLIBRARIES = lib@LIBNAME@.la

lib@LIBNAME@_la_SOURCES = @SOURCE_BASENAMES_STR@

lib@LIBNAME@_la_LIBADD = @AM_LIBLIST_STR@

lib@LIBNAME@_la_LIBADD += ${PGP_LIB} ${PNG_LIB} ${X_FPLOT_LIB} ${X11_LIB} ${FFTW3_LIBS}

lib@LIBNAME@_la_LDFLAGS = -avoid-version

#
# eof
#
